### ISSUE TITLE
Can't download zip or save to file

### ISSUE THREAD

**Issue by Dave-Poore-BSM** [a-student/SvgToVectorDrawableConverter.Web#5]
Seeing this error:

vendor.5e435ffce551c6a2a646.bundle.js:1 ERROR TypeError: Cannot read property 'files' of undefined
    at l.cancel (main.9e0ed7150967e0480d0c.bundle.js:1)
    at l.resubmit (main.9e0ed7150967e0480d0c.bundle.js:1)
    at Object.handleEvent (main.9e0ed7150967e0480d0c.bundle.js:1)
    at Object.b [as handleEvent] (vendor.5e435ffce551c6a2a646.bundle.js:1)
    at Object.handleEvent (vendor.5e435ffce551c6a2a646.bundle.js:1)
    at Ye (vendor.5e435ffce551c6a2a646.bundle.js:1)
    at vendor.5e435ffce551c6a2a646.bundle.js:1
    at t.object.i [as _next] (vendor.5e435ffce551c6a2a646.bundle.js:1)
    at t.__tryOrUnsub (vendor.5e435ffce551c6a2a646.bundle.js:1)
    at t.next (vendor.5e435ffce551c6a2a646.bundle.js:1)

**Comment by a-student** [comment]
Hi!
What browser are you using?

**Comment by Dave-Poore-BSM** [comment]
Chrome 65.0.3325.181

**Comment by ahasbini** [comment]
Same here with chrome 65.0.3325.181, pressing the download button seems to be opening a tab to download the zip but immediately closes and doesn't download anything. Got it working with Microsoft Edge 38.14393.2068.0 though.

**Comment by a-student** [comment]
I double checked in this version of Chrome - everything is fine. Seems that some extension is blocking the action. What extensions are you using?

**Comment by ahasbini** [comment]
Sorry took a while to respond. Yes your right the [AdBlock](https://chrome.google.com/webstore/detail/adblock/gighmmpiobklfepjocnamgkkbiglidom) extension was causing the problem. Tried first with incognito mode and the website worked flawlessly and downloaded the files. Added ignore rule in AdBlock and now everything is working fine, no need for Edge anymore! 😄
